/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:72be6edc-8229-4948-b5e9-91774b65e2b9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BH1nilxak",
    "aws_user_pools_web_client_id": "800furokmsehr2itst9ogu84g",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2e3mlv44ancn3glqxavtw2jpjm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7p7dmdabhjguze7yhx7w7acsgu"
};


export default awsmobile;
